In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Question 1

In [6]:
 pd.__version__

'3.0.6'

Question 2

In [7]:
df.shape

(10000, 11)

In [8]:
len(df)

10000

Question 3

In [9]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

Question 4

In [10]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Question 5

In [11]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [12]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

Question 6

In [13]:
df['horsepower'].median()

np.float64(254.0)

In [14]:
df['horsepower'].mode()[0]

np.float64(252.0)

In [15]:
mode = df['horsepower'].mode()[0]
df['horsepower'] = df['horsepower'].fillna(mode)

In [16]:
df['horsepower'].median()

np.float64(252.0)

Question 7

In [17]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [18]:
df[df['origin'] == 'Asia']['vehicle_weight'].sum()

np.int64(12679600)

In [20]:
df.describe().round(2)

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,9736.00,10000.00
mean,1999.55,3.50,2268.81,6.04,254.23,4286.75,18.89,30.00
std,14.21,0.95,183.45,0.54,21.83,266.21,1.28,2.93
min,1975.00,2.00,1590.00,4.00,171.00,3320.00,14.00,19.80
25%,1987.00,3.00,2150.00,6.00,241.00,4110.00,18.00,28.00
50%,2000.00,4.00,2270.00,6.00,252.00,4280.00,18.90,30.00
75%,2012.00,4.00,2390.00,6.00,268.00,4470.00,19.70,31.90
max,2024.00,5.00,3110.00,8.00,334.00,5460.00,23.80,41.20

In [39]:
import numpy as np

In [40]:
np.__version__

'2.5.3'

In [44]:
np.ones( )

array([1., 1., 1., 1.])

In [ ]:
np.random.rand