In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.6'

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           10000 non-null  float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Q1

In [5]:
pd.__version__

'3.0.6'

Q2

In [6]:
df.shape

(10000, 11)

In [ ]:
len(df.index)

10000

Q3

In [10]:
df["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

Q4

In [11]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Q5

In [12]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [13]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

Q6

In [16]:
df['horsepower'].median()

np.float64(254.0)

In [17]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [18]:
mode = df['horsepower'].mode()[0]

In [38]:
df['horsepower'] = df['horsepower'].fillna(mode)
df['horsepower'].median()

np.float64(252.0)

Q7

In [22]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [49]:
df[['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
0               3870        2006
1               4210        2008
2               4240        1996
3               4490        1989
4               4510        1994
...              ...         ...
9995            4690        2005
9996            4370        1993
9997            4590        2014
9998            4450        2004
9999            4370        2011

[10000 rows x 2 columns]

In [122]:
asia = df.loc[df['origin'] == 'Asia', df.columns]
asia

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [124]:
asia_subset = asia[['vehicle_weight', 'model_year']].head(7)
asia_subset

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [125]:
print(asia_subset)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [126]:
X = asia_subset.to_numpy()
X.shape

(7, 2)

In [ ]:
XTX = X.T @ X
XTX.shape

(2, 2)

In [128]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv.shape

(2, 2)

In [129]:
X.T.shape

(2, 7)

In [130]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y.shape

(7,)

In [131]:
w = XTX_inv @ X.T
w.shape

(2, 7)

In [132]:
a = w @ y
a.sum()

np.float64(0.36919696904925486)

In [24]:
df[df['origin'] == 'Asia']['vehicle_weight'].max()

np.int64(5280)

In [26]:
df.describe().round(2)

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,9736.00,10000.00
mean,1999.55,3.50,2268.81,6.04,254.23,4286.75,18.89,30.00
std,14.21,0.95,183.45,0.54,21.83,266.21,1.28,2.93
min,1975.00,2.00,1590.00,4.00,171.00,3320.00,14.00,19.80
25%,1987.00,3.00,2150.00,6.00,241.00,4110.00,18.00,28.00
50%,2000.00,4.00,2270.00,6.00,252.00,4280.00,18.90,30.00
75%,2012.00,4.00,2390.00,6.00,268.00,4470.00,19.70,31.90
max,2024.00,5.00,3110.00,8.00,334.00,5460.00,23.80,41.20

Numpy

In [53]:
import numpy as np

In [57]:
np.zeros(3)

array([0., 0., 0.])

In [59]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [61]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

In [70]:
np.random.seed(2)
np.random.rand(3,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482]])